# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.18

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/xilinxtool/xilinxtoolsshared/TMP

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/xilinxtool/xilinxtoolsshared/TMP

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/xilinxtool/xilinxtoolsshared/TMP/CMakeFiles /home/xilinxtool/xilinxtoolsshared/TMP//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/xilinxtool/xilinxtoolsshared/TMP/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named test_fpga

# Build rule for target.
test_fpga: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_fpga
.PHONY : test_fpga

# fast build rule for target.
test_fpga/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_fpga.dir/build.make CMakeFiles/test_fpga.dir/build
.PHONY : test_fpga/fast

#=============================================================================
# Target rules for targets named test_task

# Build rule for target.
test_task: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_task
.PHONY : test_task

# fast build rule for target.
test_task/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_task.dir/build.make CMakeFiles/test_task.dir/build
.PHONY : test_task/fast

#=============================================================================
# Target rules for targets named TMP

# Build rule for target.
TMP: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 TMP
.PHONY : TMP

# fast build rule for target.
TMP/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TMP.dir/build.make CMakeFiles/TMP.dir/build
.PHONY : TMP/fast

src/fpga.o: src/fpga.cc.o

.PHONY : src/fpga.o

# target to build an object file
src/fpga.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TMP.dir/build.make CMakeFiles/TMP.dir/src/fpga.cc.o
.PHONY : src/fpga.cc.o

src/fpga.i: src/fpga.cc.i

.PHONY : src/fpga.i

# target to preprocess a source file
src/fpga.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TMP.dir/build.make CMakeFiles/TMP.dir/src/fpga.cc.i
.PHONY : src/fpga.cc.i

src/fpga.s: src/fpga.cc.s

.PHONY : src/fpga.s

# target to generate assembly for a file
src/fpga.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TMP.dir/build.make CMakeFiles/TMP.dir/src/fpga.cc.s
.PHONY : src/fpga.cc.s

src/task.o: src/task.cc.o

.PHONY : src/task.o

# target to build an object file
src/task.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TMP.dir/build.make CMakeFiles/TMP.dir/src/task.cc.o
.PHONY : src/task.cc.o

src/task.i: src/task.cc.i

.PHONY : src/task.i

# target to preprocess a source file
src/task.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TMP.dir/build.make CMakeFiles/TMP.dir/src/task.cc.i
.PHONY : src/task.cc.i

src/task.s: src/task.cc.s

.PHONY : src/task.s

# target to generate assembly for a file
src/task.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TMP.dir/build.make CMakeFiles/TMP.dir/src/task.cc.s
.PHONY : src/task.cc.s

tests/test_fpga.o: tests/test_fpga.cc.o

.PHONY : tests/test_fpga.o

# target to build an object file
tests/test_fpga.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_fpga.dir/build.make CMakeFiles/test_fpga.dir/tests/test_fpga.cc.o
.PHONY : tests/test_fpga.cc.o

tests/test_fpga.i: tests/test_fpga.cc.i

.PHONY : tests/test_fpga.i

# target to preprocess a source file
tests/test_fpga.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_fpga.dir/build.make CMakeFiles/test_fpga.dir/tests/test_fpga.cc.i
.PHONY : tests/test_fpga.cc.i

tests/test_fpga.s: tests/test_fpga.cc.s

.PHONY : tests/test_fpga.s

# target to generate assembly for a file
tests/test_fpga.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_fpga.dir/build.make CMakeFiles/test_fpga.dir/tests/test_fpga.cc.s
.PHONY : tests/test_fpga.cc.s

tests/test_task.o: tests/test_task.cc.o

.PHONY : tests/test_task.o

# target to build an object file
tests/test_task.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_task.dir/build.make CMakeFiles/test_task.dir/tests/test_task.cc.o
.PHONY : tests/test_task.cc.o

tests/test_task.i: tests/test_task.cc.i

.PHONY : tests/test_task.i

# target to preprocess a source file
tests/test_task.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_task.dir/build.make CMakeFiles/test_task.dir/tests/test_task.cc.i
.PHONY : tests/test_task.cc.i

tests/test_task.s: tests/test_task.cc.s

.PHONY : tests/test_task.s

# target to generate assembly for a file
tests/test_task.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_task.dir/build.make CMakeFiles/test_task.dir/tests/test_task.cc.s
.PHONY : tests/test_task.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... TMP"
	@echo "... test_fpga"
	@echo "... test_task"
	@echo "... src/fpga.o"
	@echo "... src/fpga.i"
	@echo "... src/fpga.s"
	@echo "... src/task.o"
	@echo "... src/task.i"
	@echo "... src/task.s"
	@echo "... tests/test_fpga.o"
	@echo "... tests/test_fpga.i"
	@echo "... tests/test_fpga.s"
	@echo "... tests/test_task.o"
	@echo "... tests/test_task.i"
	@echo "... tests/test_task.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

